/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fsvtool.gui;

import fsvtool.controller.AuthentificationController;

/**
 *
 * @author Veli
 */
public class GUILogin extends javax.swing.JFrame {
    private AuthentificationController controller;
    public static final String LOGIN = "Einloggen";
    public static final String EXIT = "Beenden";
    public static final String REGISTRATION = "Anmeldung";
    private boolean ErrorShowResult;
    
    /**
     * Creates new form GUILogin
     */
    public GUILogin() {
        initComponents();
        setLocationRelativeTo(null);
        this.errorLogin.setVisible(false);
    }
    
    public void setController(AuthentificationController ac){
       this.controller = ac;
    }
        
    public String getUsername(){
        return usernameInput.getText();
    } 

    public String getPassword() {
        return new String(passwordInput.getPassword());
    }
    
    public boolean setErrorShowResult(boolean result){
        return ErrorShowResult = result;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        labelLogin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameInput = new javax.swing.JTextField();
        labelKennwort = new javax.swing.JLabel();
        passwordInput = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        errorLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FSVTool - Login");
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);

        jLayeredPane1.setMaximumSize(new java.awt.Dimension(500, 300));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(500, 300));

        labelLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelLogin.setText("Login");
        labelLogin.setBounds(230, 10, 60, 30);
        jLayeredPane1.add(labelLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Benutzername");
        jLabel3.setBounds(140, 90, 90, 15);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        usernameInput.setBounds(240, 80, 190, 30);
        jLayeredPane1.add(usernameInput, javax.swing.JLayeredPane.DEFAULT_LAYER);

        labelKennwort.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelKennwort.setText("Kennwort");
        labelKennwort.setBounds(140, 120, 90, 15);
        jLayeredPane1.add(labelKennwort, javax.swing.JLayeredPane.DEFAULT_LAYER);
        passwordInput.setBounds(240, 110, 190, 30);
        jLayeredPane1.add(passwordInput, javax.swing.JLayeredPane.DEFAULT_LAYER);

        loginButton.setText(GUILogin.LOGIN);
        loginButton.setToolTipText("");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginButton.setBounds(140, 160, 120, 40);
        jLayeredPane1.add(loginButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        registerButton.setText(GUILogin.REGISTRATION);
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        registerButton.setBounds(380, 270, 110, 20);
        jLayeredPane1.add(registerButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        exitButton.setText(GUILogin.EXIT);
        exitButton.setToolTipText("");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        exitButton.setBounds(310, 160, 120, 40);
        jLayeredPane1.add(exitButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        errorLogin.setForeground(new java.awt.Color(255, 0, 51));
        errorLogin.setText("Benutzername oder Kennwort falsch !!!");
        errorLogin.setBounds(240, 60, 230, 20);
        jLayeredPane1.add(errorLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fsvtool/background.png"))); // NOI18N
        jLabel1.setBounds(0, 0, 500, 300);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        controller.action(evt);
    }//GEN-LAST:event_registerButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        controller.action(evt);
        this.errorLogin.setVisible(ErrorShowResult);
    }//GEN-LAST:event_loginButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        controller.action(evt);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLogin;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel labelKennwort;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField usernameInput;
    // End of variables declaration//GEN-END:variables
}
