/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fsvtool.gui;

import fsvtool.controller.MainController;
import java.awt.Image;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.JPopupMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author Marcel
 */
public class GUIMainFrame extends javax.swing.JFrame {
    private MainController controller;
    public static final String NEUES_SPIEL = "Neues Spiel";
    public static final String TEILNEHMEN = "Teilnehmen";
    public static final String STORNIEREN = "Stornieren";
    public static final String EINSTELLUNGEN = "Einstellungen";
    public static final String LOGOUT = "Logout";
    public static final String MEIN_ACCOUNT = "Mein Account";
    
    

    /**
     * Creates new form GUIMainFrame
     */
    public GUIMainFrame() {
        initComponents();
        initPopupMenu();
        
        
       
    }
    
    public void setController(MainController c) {
        this.controller = c;
    }
    

    private void initPopupMenu(){
        pAccountPopup = new JPopupMenu();
        pAccountPopup.add(new JMenuItem(new AbstractAction("Einstellungen") {
            public void actionPerformed(ActionEvent e) {
                controller.action(e);
            }
        }));
        pAccountPopup.add(new JMenuItem(new AbstractAction("Logout") {
            public void actionPerformed(ActionEvent e) {
                controller.action(e);
            }
        })); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bTeilnehmen = new javax.swing.JButton();
        bStornieren = new javax.swing.JButton();
        bNewGame = new javax.swing.JButton();
        bMeinAccount = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FSV tool");
        setBackground(new java.awt.Color(255, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setOpaque(true);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setToolTipText("");
        jScrollPane1.setOpaque(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Auswählen", "Spielname", "Anzahl Spieler", "Datum/Uhrzeit", "Ort", "Teilname"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(70);
        jTable1.getColumnModel().getColumn(2).setMinWidth(100);
        jTable1.getColumnModel().getColumn(2).setMaxWidth(100);

        jScrollPane1.setBounds(100, 60, 859, 480);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bTeilnehmen.setText(this.TEILNEHMEN);
        bTeilnehmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTeilnehmenActionPerformed(evt);
            }
        });
        bTeilnehmen.setBounds(100, 550, 169, 34);
        jLayeredPane1.add(bTeilnehmen, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bStornieren.setText(this.STORNIEREN);
        bStornieren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStornierenActionPerformed(evt);
            }
        });
        bStornieren.setBounds(270, 550, 169, 34);
        jLayeredPane1.add(bStornieren, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bNewGame.setText(GUIMainFrame.NEUES_SPIEL);
        bNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNewGameActionPerformed(evt);
            }
        });
        bNewGame.setBounds(790, 550, 169, 34);
        jLayeredPane1.add(bNewGame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bMeinAccount.setText(this.MEIN_ACCOUNT);
        bMeinAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bMeinAccountMousePressed(evt);
            }
        });
        bMeinAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMeinAccountActionPerformed(evt);
            }
        });
        bMeinAccount.setBounds(840, 10, 120, 40);
        jLayeredPane1.add(bMeinAccount, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fsvtool/background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBounds(0, 0, 990, 590);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTeilnehmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTeilnehmenActionPerformed
        this.controller.action(evt);
    }//GEN-LAST:event_bTeilnehmenActionPerformed

    private void bNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNewGameActionPerformed
        this.controller.action(evt);
    }//GEN-LAST:event_bNewGameActionPerformed

    private void bStornierenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStornierenActionPerformed
        this.controller.action(evt);
    }//GEN-LAST:event_bStornierenActionPerformed

    private void bMeinAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMeinAccountActionPerformed
        this.controller.action(evt);
    }//GEN-LAST:event_bMeinAccountActionPerformed

    private void bMeinAccountMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMeinAccountMousePressed
        pAccountPopup.show(evt.getComponent(),evt.getX(), evt.getY());
    }//GEN-LAST:event_bMeinAccountMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                
                GUIMainFrame mF = new GUIMainFrame();
                mF.setIconImage(new ImageIcon("Logo.png").getImage());
                mF.setVisible(true);
                
            }
        });
    }
    private JPopupMenu pAccountPopup;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bMeinAccount;
    private javax.swing.JButton bNewGame;
    private javax.swing.JButton bStornieren;
    private javax.swing.JButton bTeilnehmen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
